include: package:lints/recommended.yaml

# Additional rules
linter:
  rules:
    # Avoid relative imports
    avoid_relative_lib_imports: true
    
    # Prefer single quotes
    prefer_single_quotes: true
    
    # Require trailing commas
    require_trailing_commas: true
    
    # Use proper naming conventions
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_declarations: true
    
    # Documentation
    public_member_api_docs: false
    
    # Avoid empty statements
    avoid_empty_else: true
    
    # Use proper imports
    prefer_relative_imports: false