name: pt_1_dart_project
description: A Dart project for PPB PT 1 assignment
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Add your dependencies here
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

# Uncomment the following section to specify files to
# include or exclude when publishing the package.
# publish_to: none

# The following section contains Dart-specific configuration.
executables:
  pt_1_dart_project: main